### ISSUE TITLE
Type Error: metaclass conflict

### ISSUE THREAD

**Issue by JerryZhang-1222** [XLearning-SCU/scBridge#4]
Dear Authos

I have converted my Seurat objects using the following code:
```
SaveH5Seurat(snRNA.out, filename = "./scBridge/snRNA.out.h5Seurat")
Convert("./scBridge/snRNA.out.h5Seurat", dest = "h5ad")

SaveH5Seurat(snATAC.out, filename = "./scBridge/snATAC.out.h5Seurat")
Convert("./scBridge/snATAC.out.h5Seurat", dest = "h5ad")
```
The metada from snRNA.out and snATAC.out both only have one column named as CellTypes.

I followed the exact same method and ran into this error
```
class _AxesSubplot(Axes, axes.SubplotBase, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

I checked my h5ad file in python:
```
>>> adata = ad.read_h5ad("xxx/snATAC.out.h5ad")
>>> print(adata.obs.columns)
Index(['CellType'], dtype='object')
>>> print(adata.obs)
                              CellType
005_dACC_AAACGAAAGAAGCCGT-1         14
005_dACC_AAACGAAAGACTCTTG-1         14
005_dACC_AAACGAAAGTGGTGTG-1         14
005_dACC_AAACGAACAAGCAGGT-1         14
005_dACC_AAACGAACAGGACTGA-1         14
...                                ...
009_vmPFC_TTTGTGTGTCAACTAC-1         0
009_vmPFC_TTTGTGTGTCATAAGA-1         8
009_vmPFC_TTTGTGTGTGATGCTT-1         1
009_vmPFC_TTTGTGTTCAGGTCTA-1        15
009_vmPFC_TTTGTGTTCGGTGATT-1        11

[91765 rows x 1 columns]
It matches my 91765 cells.

>>> print(adata.var)
      _index features
0      HTR2C    HTR2C
1     HS3ST2   HS3ST2
2       CNR1     CNR1
3     ADGRL4   ADGRL4
4     SLC1A2   SLC1A2
...      ...      ...
1029  SLC6A5   SLC6A5
1030   MASP1    MASP1
1031  RASSF3   RASSF3
1032  COL6A3   COL6A3
1033   LRRN2    LRRN2

[1034 rows x 2 columns]
```
which matches the common gene set I chose.

Could you please provide some suggestion on that?
Thanks a lot!

Best,
Feiyang.

**Comment by Yunfan-Li** [comment]
Seurat h5ad and scanpy h5ad files may have conflicts. Since the cell type and gene set have been successfully transformed, I suggest separately saving and loading the count data. You could create a scanpy object using the `sc.Anndata` method with the loaded count data, and then manually add the cell type and gene set information.

**Comment by JerryZhang-1222** [comment]
Thanks for you prompt response! I will try it out.

Bets regards
Feiyang

Yunfan Li ***@***.***> 于2024年8月20日周二 12:01写道：

**Comment by JerryZhang-1222** [comment]
Problem solved.
# 1 Exported the Seurat Object from R
The R objects have shared rownames.
```
mat <-  Matrix::t(snRNA.out@assays$RNA@counts)
#Please make sure to transpose the sparse matrix data

anno <- snRNA.out@meta.data
Matrix::writeMM(mat,file='<path>/RNA_hs.mtx')
write.csv(anno,file = "<path>/RNA_anno_hs.csv")

mat <- Matrix::t(snATAC.out@assays$RNA@counts)
anno <- snRNA.out@meta.data
Matrix::writeMM(mat,file='<path>/ATAC_hs.mtx')
write.csv(anno,file = "<path>/RNA_anno_hs.csv")
```

# 2 Load the mtx data in python
```
import scanpy as sc
import pandas as pd
import anndata as ad
import numpy as np
from scipy.sparse import csr_matrix

# for RNA
sp_RNA = sc.read_mtx("<path>/RNA_hs.mtx",dtype='float64')
anno_RNA = pd.read_csv("<path>/RNA_anno_hs.csv")
# add meta data
anno_RNA.columns = ["id","CellType"] #111020 rows, 111020 cells
sp_RNA.obs = anno_RNA

# for ATAC
sp_ATAC = sc.read_mtx("<path>/ATAC_hs.mtx",dtype='float64')
anno_ATAC = pd.read_csv("<path>/ATAC_anno_hs.csv")
#add meta data
anno_ATAC.columns = ["id","CellType"] #111020 rows, 111020 cells
sp_ATAC.obs = anno_ATAC

#export to h5ad
sp_RNA.write_h5ad("<path>/spRNA_hs.h5ad")
sp_ATAC.write_h5ad("<path>/spATAC_hs.h5ad")

```
I am not a skilled user of python or scanpy, maybe there will be an easier way.

# 3 Fix Version Conflict of Pandas
Then I met this error: 
```
ImportError: cannot import name 'is_categorical' from 'pandas.api.types'.
```
which seems to be a pandas version conflict that the pandas version>=2 does not have the method called `is_categorical`. I checked my pandas version in conda environment scBridge:
```
conda activate scBridge
python
>>> import pandas as pd
>>> pd.__version__

'2.2.1'
```
it turned out that even I installed the environment according to your .yml, conda still gives me a 2.2.1 version of pandas.It was also wired that installing pandas with `conda install pandas=1.4.4` does not change the pandas version imported to python console.
Luckily,
```
pip install pandas==1.4.4
```
fixed the issue.

Thanks a lot.

Best,
Feiyang.

**Comment by JerryZhang-1222** [comment]
Hi Yunfan,

I got the results of the figures, which seems very good. But I don't see
any new h5ad file as I can into this error at the very end.

```

======= Training Done =======

/home/liuzechen/.local/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py:80:
UserWarning: input's size at dim=0 does not match num_features. You can
silence this warning by not passing in num_features, which is not used
because affine=False

  warnings.warn(f"input's size at dim={feature_dim} does not match
num_features. "

Running UMAP visualization...

WARNING: saving figure to file figures/umap_brain_CellType.png

WARNING: saving figure to file figures/umap_brain_Domain.png

WARNING: saving figure to file figures/umap_brain_Reliability.png

=======Evaluation=======

Traceback (most recent call last):

  File "/home/liuzechen/Experiments/zfy/scBridge/main.py", line 137, in
<module>

    main(args)

  File "/home/liuzechen/Experiments/zfy/scBridge/main.py", line 93, in main

    save_result(

  File "/home/liuzechen/Experiments/zfy/scBridge/eval_utils.py", line 148,
in save_result

    f1_acc = (f1_score(target_label_int, pred_vec, average=None) *
f1_weight).sum()

ValueError: operands could not be broadcast together with shapes (17,) (16,)


```


I am quite sure this happens because of some dependency conflicts. I
followed your guide to create the environment but I failed to have the
exact same version of those tools. Anyway to solve this conflicts? Thanks
so much!


Best.

Feiyang,

Feiyang Zhang ***@***.***> 于2024年8月20日周二 12:02写道：

**Comment by Yunfan-Li** [comment]
The error seems to be caused by the inconsistency between the reference cell type number and the predicted cell type number. Does your scRNA-seq data contain a different number of cell types compared with the scATAC-seq data?

**Comment by JerryZhang-1222** [comment]
I will check that! It should have been the same, maybe some typo? I will
check.

Thank you!!!

Yunfan Li ***@***.***> 于2024年8月20日周二 20:05写道：

**Comment by JerryZhang-1222** [comment]
Dear Yunfan,

I checked, and **just as you expected**, I do have one more cell type in snATAC that not found in snRNA-seq. Is there any way for me to solve it?

Maybe modifying the script of "saving process" by myself is a way as I have already got the UMAP plot thus I am quite sure the data was in there just not exported yet, or, cancel the new cell type in snATAC-seq by replacing it with a known one. But still, any recommend ways to solve that? THX!

Yours,
Feiyang.

**Comment by Yunfan-Li** [comment]
You could add the `--novel_type' config when running the command to handle the additional cell types in scATAC-seq data.

**Comment by JerryZhang-1222** [comment]
Thanks Yunfan! I just saw that in your README.md, I should have noticed
that.

Thank you for this GREAT tool again.

Yunfan Li ***@***.***> 于2024年8月20日周二 20:55写道：

**Comment by Yunfan-Li** [comment]
You are welcome.

**Comment by JerryZhang-1222** [comment]
Issue fixed. Thanks!

**Comment by JerryZhang-1222** [comment]
I ran into the similar problem again using another dataset. The previous conda environment just somehow not working anymore. I fixed the issue by :
pip install matplotlib==3.5.3
pip install anndata==0.8.0

The error happens when importing scanpy.

the rest are the same as the tutorial. 

Just a note for myself or anyone who got into the same error.

**Comment by JerryZhang-1222** [comment]
I am very certain that this is because the matplotlib conflict because this issue is repeatable when I update the version of  matplotlib. Somehow the conda won't give me the correct version of matplotlib==3.5.3 even though I follow the config.yml file to create the environment.

**Comment by Yunfan-Li** [comment]
The current package versions are copied from my conda environment. Are you suggesting that matplotlib==3.5.3 conflicts with other packages in the config.yml file? If so, could you kindly provide a valid version so I can update the config file? Thanks a lot.

**Comment by JerryZhang-1222** [comment]
Thank you for your prompt response! The version of matplotlib==3.5.3  is **correct**, the thing is when I run
```
conda env create -f environment.yml
```
It gives me a different version of a lot of modules, including matplotlib, and using pip install matplotlib==3.5.3 will fix the issue. I think it might be hard to say why conda gives me a wrong version of matplotlib. But the environment.yml file is good. Thank you!
